<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <PropertyGroup>
        <PreserveCompilationContext>true</PreserveCompilationContext>
        <CopyRefAssembliesToPublishDirectory>true</CopyRefAssembliesToPublishDirectory>
    </PropertyGroup>
    
    <ItemGroup>
      <Folder Include="API\" />
      <Folder Include="MVC\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="alaasmagi.Base.Message.RabbitMQ" Version="1.1.7" />
      <PackageReference Include="alaasmagi.Base.Keycloak" Version="1.1.7" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.9" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.9" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
      <PackageReference Include="Sentry.AspNetCore" Version="6.6.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Application\Application.csproj" />
      <ProjectReference Include="..\Contracts\Contracts.csproj" />
      <ProjectReference Include="..\DataAccess\DataAccess.csproj" />
      <ProjectReference Include="..\DTO\DTO.csproj" />
      <ProjectReference Include="..\External\External.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="MVC\wwwroot\**\*" CopyToPublishDirectory="PreserveNewest" />
      <_ContentIncludedByDefault Remove="Views\Account\AccessDenied.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Clients\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Clients\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Clients\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Clients\_Form.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Emails\Details.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Emails\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Home\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Home\Privacy.cshtml" />
      <_ContentIncludedByDefault Remove="Views\SenderIdentities\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Views\SenderIdentities\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Views\SenderIdentities\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\SenderIdentities\_Form.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Shared\Error.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Shared\_Layout.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Shared\_ValidationScriptsPartial.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Templates\Create.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Templates\Edit.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Templates\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Views\Templates\_Form.cshtml" />
      <_ContentIncludedByDefault Remove="Views\_ViewImports.cshtml" />
      <_ContentIncludedByDefault Remove="Views\_ViewStart.cshtml" />
      <_ContentIncludedByDefault Remove="wwwroot\css\site.css" />
      <_ContentIncludedByDefault Remove="wwwroot\favicon.ico" />
      <_ContentIncludedByDefault Remove="wwwroot\js\site.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery-validation-unobtrusive\LICENSE.txt" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery\LICENSE.txt" />
    </ItemGroup>

</Project>
